// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2kd591GX7F0D_2lMMJfZV0BchQzPpRKk',
    appId: '1:11059410431:web:b7159b7a7c84216cb163ca',
    messagingSenderId: '11059410431',
    projectId: 'firebase-authentication-bloc',
    authDomain: 'fir-authentication-bloc.firebaseapp.com',
    storageBucket: 'firebase-authentication-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wadaJy_dEbB8g0OlQHg63nkNwSPGGQw',
    appId: '1:11059410431:android:c7915f5aeea49740b163ca',
    messagingSenderId: '11059410431',
    projectId: 'firebase-authentication-bloc',
    storageBucket: 'firebase-authentication-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaTrX0EsplEIpSqQ5GMJsEhau8DdQNXhM',
    appId: '1:11059410431:ios:d80cff272f0768a5b163ca',
    messagingSenderId: '11059410431',
    projectId: 'firebase-authentication-bloc',
    storageBucket: 'firebase-authentication-bloc.appspot.com',
    iosClientId: '11059410431-uperkb0h0emhas9i83shemflo76brt9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
